DROP TABLE IF EXISTS persons CASCADE;

CREATE TABLE IF NOT EXISTS persons(
id SERIAL PRIMARY KEY,
name VARCHAR(50) NOT NULL,
age INTEGER check (age > 0),
email VARCHAR(255) UNIQUE,
created_at TIMESTAMP
);

INSERT INTO persons(name, age, email) VALUES ('Aboba', 99, 'aboba@mail.com');
INSERT INTO persons(name, age, email) VALUES ('Tom', 25, 'tom@mail.com');
INSERT INTO persons(name, age, email) VALUES ('Bob', 51, 'bob@mail.com');
INSERT INTO persons(name, age, email) VALUES ('Katy', 38, 'katy@mail.com');

DROP TABLE IF EXISTS books CASCADE;

CREATE TABLE IF NOT EXISTS books(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
title VARCHAR(100) NOT NULL,
author VARCHAR(50) NOT NULL,
borrower_id INTEGER REFERENCES persons(id)
);

INSERT INTO books(title, author, borrower_id) VALUES('Мастер и Маргарита', 'Михаил Булгаков', 1),
('Преступление и наказание', 'Федор Достоевский', 1),
('Братья Карамазовы', 'Федор Достоевский', 3);
INSERT INTO books(title, author) VALUES('Идиот', 'Федор Достоевский'),
('Горе от ума', 'Александр Грибоедов');
