DROP TABLE IF EXISTS persons CASCADE;

CREATE TABLE IF NOT EXISTS persons(
id SERIAL PRIMARY KEY,
name VARCHAR(50) NOT NULL,
age INTEGER check (age > 0),
email VARCHAR(255) UNIQUE,
created_at TIMESTAMP
);

INSERT INTO persons(name, age, email) VALUES ('Aboba', 99, 'aboba@mail.com');
INSERT INTO persons(name, age, email) VALUES ('Tom', 25, 'tom@mail.com');
INSERT INTO persons(name, age, email) VALUES ('Bob', 51, 'bob@mail.com');
INSERT INTO persons(name, age, email) VALUES ('Katy', 38, 'katy@mail.com');

DROP TABLE IF EXISTS rental_objects CASCADE;

CREATE TABLE IF NOT EXISTS rental_objects(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
title VARCHAR(100) NOT NULL,
author VARCHAR(50) NOT NULL,
quantity INTEGER NOT NULL
);

INSERT INTO rental_objects(title, author, quantity) VALUES('Мастер и Маргарита', 'Михаил Булгаков', 1),
                                                    ('Преступление и наказание', 'Федор Достоевский', 1),
                                                    ('Братья Карамазовы', 'Федор Достоевский', 3),
                                                    ('Идиот', 'Федор Достоевский', 5),
                                                    ('Горе от ума', 'Александр Грибоедов', 2);

DROP TABLE IF EXISTS rent_contracts CASCADE;

CREATE TABLE IF NOT EXISTS rent_contracts(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
    borrower_id INTEGER REFERENCES persons(id),
    book_id INTEGER REFERENCES rental_objects(id),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

